### ISSUE TITLE
yarn install version mismatch error

### ISSUE THREAD

**Issue by buffalojoec** [solana-developers/dapp-scaffold-svelte#6]
@silvestrevivo 

I was going to poke around this but I'll toss it here in case you know what it is already.   

Tried cloning the repository and ran `yarn install` and got the following error:
```shell
config.kit.vite has been removed — use vite.config.js instead
```

**Comment by silvestrevivo** [comment]
@jpcaulfi there was a SvelteKit update a few days ago and this update is breaking totally the configuration. Let me check to find a solution for this and I open a PR. Thanks!!! :)

**Comment by silvestrevivo** [comment]
@jpcaulfi I was checking on the SvelteKit server and there are some issues with the last update to the vite config file, not only on development but even sending to production. I've just pushed a commit with svelteKit to the version 354, where development and production are stable. As soon as the issue is solved, I can update the repo to the `next` version.
